---
title: "Journal"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

### 2026 | 10 | 05

立flag, 今日一定要改完introduction.

改完之後再係尼度update.

### 2026 | 10 | 03 

某次一哥們問我：你能感受到科學之美嗎？我回答：這就是我讀博的理由。

這番話把我拉回本科階段。Prof Zhu是我本科導師，我當時的畢業論文是使用光學遙感做野火分析。在讀博開始前一周我回PolyU看望Prof Zhu, 教授順便把我拉去了他的組會，這麽介紹我：最早的學生之一，被我忽悠著去做科研的。

那麽多年過去，我終於走上了科研的路。只是有點遺憾，我大概無緣光學遙感了。

### 2026 | 10 | 02 

**講講這個repo的本意**

我的本意是創建一個網站來記錄PhD學習的過程。初步構想是使用Rmarkdown及一個開源github page搭建一個網站。但是對兩者都知之甚少。基於此，我便先記錄在Rmarkdown上面，等後續有時間再慢慢補全。

日記部分主要會以中文形式呈現，學習筆記以英文爲主，中文為輔。

**再講講AI在科研中的運用**

這段時間我在修改PhD開題報告。遇到的一個很大的問題是導師寫了很多so what類的評論。我試著把我寫的狗屎原文投喂給3個AI，分別是Claude, Chatgpt與Gemini.

Claude (free) 給我的感覺是一個非常嚴厲的導師，話不多而句句切中痛點。Chatgpt (free) 大概被我用壞了，回復很長，囉囉嗦嗦講了上千字，有點點在奉承。Gemini (plus) 只改了幾個語法錯誤，更適合來讀文獻。

（16：59 update）我今日白天在學校無心科研，時間都用來研究怎麽用Rmarkdown創建agrivoltaic學習網站了，一日下來還弄得有模有樣。但是我在修改proposal上卡了太久了，連自己都不想打開文件看一個月前的狗屎，這種情況下除了科研，幹啥都有趣。

以上。