---
title: "Resources"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---

### R and R-Studio

[R](http://www.r-project.org) is a free open-source programming language that can be used for statistical analysis, data-simulation, graphing, and lots of other stuff. Another free program is [R-studio](http://www.rstudio.com), that provides a nice graphic interface for R. Download R first, then download R-studio. Both can run on PCs, Macs or Linux. Students will be learning R in the stats labs using the lab manual []().

### Climatology

1. [Ecological Climatology](https://www.cambridge.org/core/books/ecological-climatology/D146443B007985BC366B2512345692C0?pageNum=1&searchWithinIds=D146443B007985BC366B2512345692C0&productType=BOOK_PART&searchWithinIds=D146443B007985BC366B2512345692C0&productType=BOOK_PART&sort=mtdMetadata.bookPartMeta._mtdPositionSortable%3Aasc&pageSize=30&template=cambridge-core%2Fbook%2Fcontents%2Flistings&ignoreExclusions=true) is great.
2. [Terrestrial Biosphere-Atmosphere Fluxes](https://www.cambridge.org/core/books/terrestrial-biosphereatmosphere-fluxes/43C9DC719235C8832D6BD6D90B6EFA49) is great.
3. Food and Agriculture Organization of the United Nations (FAO) [Crop evapotranspiration](https://www.fao.org/4/x0490e/x0490e00.htm#Contents) website, it's worth checking out.

### Agrivoltaic project website

1. [ZNEAG CRC](https://zneagcrc.com.au/research_project/agrivoltaics-integrating-profitable-agricultural-production-and-renewable-energy-generation/): Agrivoltaics: Integrating Profitable Agricultural Production and Renewable Energy Generation
2. [WAARC](https://gemini.google.com/app/1895b1a9c6c9dc52?hl=en-AU): Agrivoltaics: Integrating Profitable Agricultural Production and Renewable Energy Generation brings together leading researchers, growers and energy experts from across Australia to explore the co-location of solar panels and agricultural production – known as agrivoltaics.

### Personal links
1. [LinkedIn](www.linkedin.com/in/kwan-yu-chuk-aa88a62a8)
2. [Personal website](https://kwanyuchuk.github.io/)
3. [Github page](https://github.com/KwanYuChuk)

### **Google is great. AI is great**