---
title: "Panel configuration"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# **AV system architectures**

2026 | 10 | 07 Last compiled: `r Sys.Date()`

**Fixed AV**: include ground-mounted, elevated (stilt-mounted), rooftops, and greenhouse-integrated configurations. Tilt and orientation are constant, with crop exposure determined mainly by panel spacing and mounting height. Elevated designs enhance machinery access and light distribution.

## **General configurations**

Key parameters—panel height (2–8 m), spacing (3–12 m), shading ratio (0.2–0.8), and tilt (0–45◦), to regulate light distribution, microclimate, crop responses.

**Dynamic AV**: single—or dual-axis tracking systems that adjust panel orientation in real time, enhancing PV yield while dynamically adjusting shading patterns.  Higher capital costs, increased mechanical complexity, and greater maintenance requirements.

## **Tracking strategies**

2026 | 10 | 05 Last compiled: `r Sys.Date()`

Sun tracking: The standard operation of the solar tracker, designed to maximize energy output

Anti tracking: The inverse of sun tracking, aimed at maximizing ground irradiance or minimizing solar irradiation interception by the PV system.

Scheduled tracking: A hybrid strategy that alternates between sun tracking and anti tracking throughout the day. For example, between 11am to 3pm use sun tracking and remaining hours use anti tracking. <span style="color:blue">This is to avoid midday hottest and most irradiated hours that incoming light may exceed the crop's usable range</span>. 

Daily light integral tracking: Initially follows the anti tracking strategy until the crop's required DLI is met, then switches to sun tracking for the remainder of the day prioritizing energy conversion (light for crop use first and then energy).

Knee point tracking: It chooses the optimal tilt angle based on the ambient temperature in the field that is derived out of the optimal PAR of the LRC using the KP.

*Note: I'm really interested with different tracking strategies, especially those prioritize crop light requirements (and not so many research papers about this - there is a big research gap). But I read an Australian review paper and realize Australian farmers are more care about general configurations, like panel height, row spacing, material...I need to consider what farmers need, not just my interests.*

# **Panel materials**

2026 | 10 | 02 Last compiled: `r Sys.Date()`

**Conventional c-Si**: single-sided monocrystalline or polycrystalline silicon modules, characterised by a single active surface exposed to direct solar radiation. <span style="color:blue">Usually moderate to high shading</span>. Common in tracking systems.

**Bifacial PV**: two active surfaces capable of absorbing not only direct and diffuse radiation, but also that reflected from the ground. <span style="color:blue">Usually low to moderate shading in vertical; moderate to high shading in tilt</span>. Common in horticulture.

**Semi-tranparent PV**: transmit a significant amount of PAR, while filtering out wavelengths that cannot be used by plants and converting them into electricity. <span style="color:blue">Usually low to moderate shading</span>.

**Concentrating PV**: convey solar radiation to high-efficiency multi-junction cells, allowing the diffuse component of the radiation to pass through to the plants. <span style="color: blue">Designed for low crop light penaty</span>.





